spring:
  datasource:
    url: <%= ENV["URL"] %>
    driverClassName: org.postgresql.Driver
    username: <%= ENV["USERNAME"] %>
    password: <%= ENV["PASSWORD"] %>

cloud.aws:
  credentials:
    accessKey: <%= ENV["accessKey"] %>
    secretKey: <%= ENV["secretKey"] %>
  region:
    static: ap-northeast-1